### ISSUE TITLE
A hacer para la entrega de Etapa 2

### ISSUE THREAD

**Issue by pablo-maker** [birchnerg/NET2021_Codificacion_sistema_simple#15]
1. Crear un Login con persistencia y validación de los datos.
2. Menu para navegar a través de todos los ABM del sistema.
3. Agregar 1 ABM por integrante.

**Comment by birchnerg** [comment]
- Confirmación para validar la eliminación no estaría de mas.

**Comment by birchnerg** [comment]
Realizado
